name: Build Action

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**/*"
  push:
    branches:
      - main
    paths:
      - "src/**/*"

env:
  GITHUB_TOKEN: ${{ secrets.PATNAME }}

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: yarn run lint
      - run: yarn test

  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: yarn run build
      - name: Commit files
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
              git commit -m "Update build [skip-ci]" -a
              git push
          fi
